# Generated by Django 5.2 on 2025-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsapi_mapping',
            field=models.CharField(blank=True, help_text='Corresponding NewsAPI category name (business, technology, etc.)', max_length=20, null=True),
        ),
    ]
